block-explosion:
  # Should we log and trace this type of explosion?
  enable: true
  # Cancel the explosion if its source can't be tracked.
  disable-unknown: true
  # The message that will be broadcast to players.
  alert: "&cAn explosion near you has been blocked because it was caused by an unknown object. Please screenshot this and report it to an admin, along with your current in-game location."
entity-explosion:
  enable: true
  disable-unknown: true
  alert: "&cAn explosion near you has been blocked because that caused by unknown object. Please screenshot this and report it to an admin, along with your current in-game location."
fire:
  enable: true
  disable-unknown: true
  alert: "&cAn fire spreading/burning has been blocked because that caused by unknown object. Please screenshot this and report it to an admin, along with your current in-game location."
itemframe:
  enable: true
  disable-unknown: true
  alert: "&cBlocked item-frame destroy because that caused by unknown object. Please screenshot this and report it to an admin, along with your current in-game location."
hanging:
  enable: true
  disable-unknown: true
  alert: "&cBlocked hanging destroy because that caused by unknown object. Please screenshot this and report it to an admin, along with your current in-game location."
